Implement codegen validation for `(goes)` option
SpineEventEngine/validation pull request #168
Opened 2024-12-03 17:24 UTC by yevhenii-nadtochii

2024-12-04 11:47 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov please confirm specs for `(goes)` option. The present documentation doesn't say about the supported target (which declares the option) and companion (which is specified in `with`) field types.

<details>
<summary>The docs fragment from `options.proto`.</summary>

```
// Specifies that a message field can be present only if another field is present.
//
// Unlike the `required_field` that handles combination of required fields, this option is useful
// when it is needed to say that an optional field makes sense only when another optional field is
// present.
//
// Example: Requiring mutual presence of optional fields.
//
//    message ScheduledItem {
//        ...
//        spine.time.LocalDate date = 4;
//        spine.time.LocalTime time = 5 [(goes).with = "date"];
//    }
//
message GoesOption {

    // The default error message format string.
    //
    // The first parameter is the name of the field for which we specify the option.
    // The second parameter is the name of the field set in the "with" value.
    //
    option (default_message) = "The field `%s` can only be set when the field `%s` is defined.";

    // A name of the field required for presence of the field for which we set the option.
    string with = 1;

    // A user-defined validation error format message.
    string msg_format = 2 [deprecated = true];

    // A user-defined validation error format message.
    //
    // May include the token `{value}` for the actual value of the field. The token will be replaced
    // at runtime when the error is constructed.
    //
    string error_msg = 3;
}
```
</details>

In its docs, the option is compared to `required` and should likely mimic its behavior. So, I suggest the following list of supported target and companion fields:

1. Messages and enums. Default instances are considered to be non-set.
2. Repeated fields and maps. Empty collections are non-set fields.
3. `string` and `bytes`. An empty string and empty byte array are non-set.

The same field types are supported by `(required)`. 

Numeric and boolean fields are not intended to be either target fields or companions, as it is impossible to determine whether such a field was set or not. The `(required)` option also treats these fields as always set because their default values are quite "normal". The remaining question is whether we should silently ignore these fields when used with the option (as `(required)` does) or throw an error instead.

2024-12-04 18:15 UTC, armiol commented
@yevhenii-nadtochii Yes, I would consider it to be like a conditional `required`. With the applications exactly like `required` has.

2024-12-06 15:49 UTC, armiol requested changes
@yevhenii-nadtochii mostly LGTM. See my comments, though.

2024-12-06 15:49 UTC, armiol commented on java-tests/validating/src/test/kotlin/io/spine/test/options/goes/TestDataMutual.kt
> +internal object TestDataMutual {
I would move it to `.given` package and rename to `...Env`.

2024-12-06 15:49 UTC, armiol commented on java-tests/validating/src/test/kotlin/io/spine/test/options/goes/TestDataOneWay.kt
> +internal object TestDataOneWay {
Same as above.

2024-12-06 16:31 UTC, yevhenii-nadtochii commented
@armiol PTAL

2024-12-06 16:53 UTC, armiol approved these changes

2024-12-09 15:09 UTC, merged