Required IDs and more informative error messages
SpineEventEngine/validation pull request #17
Opened 2021-12-08 14:36 UTC by dmdashenkov

2021-12-08 16:36 UTC, armiol requested changes
@dmdashenkov LGTM in general. Please see my comments.

2021-12-08 16:36 UTC, armiol commented on model/src/main/java/io/spine/validation/RequiredIdPatternPolicy.java
> +final class RequiredIdPatternPolicy extends RequiredIdPolicy {
Let's describe the difference between this policy and `RequiredIdOptionPolicy`. As discussed, we need to guide the potential users on which to apply and when.

2021-12-08 16:36 UTC, armiol commented on model/src/main/proto/spine/validation/config.proto
> +// the Validation library to be satisfied with the config, it mast always have
`must`.

2021-12-08 17:27 UTC, alexander-yevsyukov approved these changes
LGTM, with a few suggestions to consider before merging.

2021-12-08 17:27 UTC, alexander-yevsyukov commented on model/src/main/java/io/spine/validation/RequiredIdPatternPolicy.java
> +    private static ImmutableList<FilePattern> allPatterns(MessageMakers markers) {
Please consider transforming this conversion to Kotlin extension for `MessageMakers`.

2021-12-08 17:27 UTC, alexander-yevsyukov commented on model/src/main/java/io/spine/validation/ValidationPolicy.java
> +        extends Policy<E> {
Please put `extends` on the previous line. It should fit.

2021-12-08 17:27 UTC, alexander-yevsyukov commented on model/src/main/java/io/spine/validation/Rules.java
> +    static RuleAdded toEvent(Rule rule, TypeName type) {
Please consider transforming this into a Kotlin extension for the `Rule` type.

Please also document the `type` parameter.

2021-12-08 17:27 UTC, alexander-yevsyukov commented on model/src/main/java/io/spine/validation/RequiredRule.java
>                  .newBuilder()
Please put `newBuilder()` on the previous line.

2021-12-08 17:27 UTC, alexander-yevsyukov commented on model/src/main/java/io/spine/validation/RequiredRule.java
> +    private static Rule wrap(CompositeRule r) {
Can these two methods be a part of a mixin interface common for `SimpleRule` and `CompositeRule`?

2021-12-08 17:27 UTC, alexander-yevsyukov commented on model/src/main/java/io/spine/validation/RequiredPolicy.java
> +        return new IllegalStateException(format(
We have `Exceptions.newIllegalStateException()` which does exactly this. Why not use it?

2021-12-09 13:02 UTC, dmdashenkov commented
@armiol, PTAL.

2021-12-09 17:14 UTC, armiol approved these changes

2021-12-10 10:20 UTC, merged