Required field errors
SpineEventEngine/validation pull request #170
Opened 2024-12-09 20:29 UTC by alexander-yevsyukov

This PR makes the `RequiredPolicy` to treat the `(required)` option applied to a boolean or number field as `Compilation.Error`. Now the build terminates on such an error.

The PR adds the tests that verify this behaviour (see `RequiredPolicySpec` for details). Also, the PR removes the stub proto types that had wrongly applied `(required)` field because they now fail the build.

## Build changes
 * Latest `config` was applied.

2024-12-17 19:24 UTC, alexander-yevsyukov commented on model/src/main/kotlin/io/spine/validation/required/RequiredPolicy.kt
> +        val file = field.declaringFile(typeSystem!!)
We moved functions back under the class because now we need the `typeSystem` property.

2024-12-17 19:26 UTC, alexander-yevsyukov commented on model/src/main/kotlin/io/spine/validation/required/RequiredRule.kt
> +    fun isRequired(field: Field, assumed: Boolean): Boolean =
I've moved this function to the top because it's the one from which we start dealing with the option processing.

2024-12-18 10:43 UTC, yevhenii-nadtochii requested changes

2024-12-18 10:43 UTC, yevhenii-nadtochii commented on java-tests/validating/src/testFixtures/proto/spine/test/tools/validate/required.proto
> +    int32 required_numbers_are_not_validated = 1;
It is no longer required.

2024-12-18 10:43 UTC, yevhenii-nadtochii commented on model/src/main/kotlin/io/spine/validation/required/RequiredPolicy.kt
> +                    " does not support `($REQUIRED)` validation.",
```suggestion
                    " does not support `($REQUIRED)` constraint.",
```

2024-12-18 10:43 UTC, yevhenii-nadtochii commented on model/src/test/kotlin/io/spine/validation/required/RequiredPolicySpec.kt
> +            it shouldContain doesNotSupportRequired
I would have `expectedMessage(descriptor, type)` function here. Anyway, the whole message is asserted.

2024-12-18 10:43 UTC, yevhenii-nadtochii commented on model/src/test/kotlin/io/spine/validation/required/RequiredPolicySpec.kt
> +    private fun createAndRunPipeline(
Maybe `compileWithPipeline()`? Can this function return the nullable error, so not to have a `lateinit var` property?

2024-12-18 10:43 UTC, yevhenii-nadtochii commented on model/src/testFixtures/proto/spine/validation/given/required/required_policy_spec.proto
> +message WithBoolField {
Please leave a comment what this message tests. And the same with the message below.

2024-12-18 10:43 UTC, yevhenii-nadtochii commented on model/src/testFixtures/proto/spine/validation/given/required/required_policy_spec.proto
> +message WithIntField {
I also suggest add test cases for `double` and for one non-widespread type like `sfixed64`.

2024-12-18 17:59 UTC, armiol approved these changes

2024-12-18 18:05 UTC, yevhenii-nadtochii approved these changes

2024-12-18 18:11 UTC, merged