Update ProtoData and include dependencies in the type system
SpineEventEngine/validation pull request #84
Opened 2023-04-10 08:43 UTC by dmdashenkov

2023-05-09 15:14 UTC, dmdashenkov commented
@armiol, @alexander-yevsyukov, PTAL.

2023-05-09 15:47 UTC, armiol requested changes
@dmdashenkov LGTM except for a single comment. That one may lead to others, once addressed.

2023-05-09 15:47 UTC, armiol commented on java-tests/vanilla/build.gradle.kts
> +        java.setSrcDirs(java.filter { !it.absolutePath.startsWith("${buildDir.absolutePath}/generated") })
This piece will seem odd in a few months, or so. Could you please document the idea? I.e. why would we need to do that at all?

2023-05-09 17:01 UTC, alexander-yevsyukov approved these changes
Have a look at a couple of FYI notes I added. I concur with the request from @armiol on documenting the filtering code. Apart from that, LGTM. Looking forward to the further, much wanted, improvements.

2023-05-10 11:35 UTC, dmdashenkov commented
@armiol, PTAL.

2023-05-10 12:00 UTC, armiol approved these changes

2023-05-10 12:15 UTC, merged