New ProtoData
SpineEventEngine/validation pull request #86
Opened 2023-06-08 14:22 UTC by dmdashenkov

2023-06-12 13:47 UTC, dmdashenkov commented
@armiol, PTAL.
Please note that most of the changes are just the updates of `config`, not actual code repository changes.

2023-06-12 14:07 UTC, armiol requested changes
@dmdashenkov requesting changes, so that — as discussed — you could trigger re-review once we update to ProtoData 0.9.0.

2023-06-13 18:20 UTC, dmdashenkov commented
@armiol, PTAL.

2023-06-13 18:22 UTC, armiol commented
@dmdashenkov please update the PR description with the new version. I will be reviewing the PR itself tomorrow.

2023-06-14 12:39 UTC, armiol approved these changes
@dmdashenkov LGTM with a few comments.

2023-06-14 12:39 UTC, armiol commented on java-tests/build.gradle.kts
> +                    substitute(module("io.spine.validation:spine-validation-java-bundle")).using(project(":java"))
I saw this substitution several months ago already :)

Let's have a comment, explaining the idea. Just in case.

2023-06-14 12:39 UTC, armiol commented on pom.xml
> +<!--
That's new.

Maybe, we shouldn't insert it here? It will get overwritten next time we generate it, anyway.

2023-06-14 13:23 UTC, merged